name: UXAI with open AI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'v20.9.0' # Adjust the Node.js version as needed

      - name: Install dependencies and build
        run: |
          npm install
          npm run build --if-present

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'UXAI' # Replace with your Azure App name
          slot-name: 'Production' # Replace with your desired slot name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9D66BCE0B0874E2586CCCAD25AABAFCA }} # Add your Azure publish profile secret
          package: . # You can adjust the path if needed
